package com.example.ui

object Localization {
    private val en = mapOf(
        "app_title" to "Fashion Forge",
        "app_subtitle" to "صناع الموضة والأناقة",
        "start_something" to "Start something",
        "extraordinary" to "extraordinary.",
        "choose_template" to "Bespoke Arabic tailoring tailored to absolute perfection.",
        "blank_canvas" to "Blank Canvas",
        "blank_canvas_sub" to "Start from zero",
        "quick_launch" to "Quick Launch",
        "quick_launch_sub" to "Pre-built flow",
        "team_invite" to "Team Invite",
        "templates" to "Templates",
        "recent_projects" to "Recent Projects",
        "home" to "Home",
        "orders" to "Orders",
        "market" to "Market",
        "map" to "Map",
        "switch_portal" to "Switch Portal:",
        "profile" to "Profile",
        "my_account_profile" to "My Account Profile",
        "role_portal" to "Role Portal",
        "display_name" to "Display Name",
        "phone_number" to "Phone Number",
        "address" to "Address / Location",
        "bio" to "Bio / Sizing notes...",
        "save_changes" to "Save Changes",
        "light_mode" to "Light Mode",
        "dark_mode" to "Dark Mode",
        "system_theme" to "System Theme",
        "language_setting" to "Language / اللغة",
        "arabic" to "العربية (Arabic)",
        "english" to "English (English)",
        "appearance" to "Theme / Appearance",
        "settings_desc" to "Configure interactive layouts, language & system mode",
        "save_success" to "Profile updated successfully!",
        "customer_view" to "Customer Portal",
        "tailor_view" to "Tailor Portal",
        "supplier_view" to "Supplier Portal",
        "delivery_view" to "Delivery Portal",
        "nav_home" to "Home",
        "nav_orders" to "Orders",
        "nav_market" to "Market",
        "nav_map" to "Map",
        "recent_projects_title" to "Active Orders Tracking"
    )

    private val ar = mapOf(
        "app_title" to "فاشن فورج",
        "app_subtitle" to "صناع الموضة والأناقة والقصات الفاخرة",
        "start_something" to "ابدأ تصميمك",
        "extraordinary" to "بشكل استثنائي.",
        "choose_template" to "تفصيل وخياطة عربية فاخرة تناسب ذوقك الرفيع بدقة متناهية.",
        "blank_canvas" to "تصميم جديد",
        "blank_canvas_sub" to "ابدأ التفصيل من الصفر",
        "quick_launch" to "معالج ذكي سريع",
        "quick_launch_sub" to "جلسة عمل جاهزة",
        "team_invite" to "دعوة أصدقاء",
        "templates" to "كتالوج القوالب",
        "recent_projects" to "المشاريع الأخيرة",
        "home" to "الرئيسية",
        "orders" to "الطلبات",
        "market" to "المتجر",
        "map" to "الخريطة",
        "switch_portal" to "تبديل البوابة من هنا:",
        "profile" to "الملف الشخصي",
        "my_account_profile" to "حسابي الشخصي وإعداداتي",
        "role_portal" to "البوابة النشطة حالياً",
        "display_name" to "الاسم بالكامل",
        "phone_number" to "رقم الجوال والاتصال",
        "address" to "عنوان التوصيل السكني",
        "bio" to "ملاحظات المقاسات وتغييراتها...",
        "save_changes" to "حفظ التغييرات",
        "light_mode" to "النظام المضيء",
        "dark_mode" to "النظام الداكن (الوضع الليلي)",
        "system_theme" to "تلقائي مع إعدادات جهازك",
        "language_setting" to "اللغة المفضلة / Preferred Language",
        "arabic" to "العربية (Arabic)",
        "english" to "English (English)",
        "appearance" to "المظهر والسمات البصرية",
        "settings_desc" to "تخصيص اللغات المناسبة لخدمتك والوضع الليلي",
        "save_success" to "تم حفظ ملف التعريف بنجاح وفخر!",
        "customer_view" to "بوابة العميل",
        "tailor_view" to "بوابة الترزي المحترف",
        "supplier_view" to "بوابة مورد الأقمشة",
        "delivery_view" to "بوابة مندوب التوصيل",
        "nav_home" to "الرئيسية",
        "nav_orders" to "طلباتي اليوم",
        "nav_market" to "أقمشة ومستلزمات",
        "nav_map" to "خريطة الورشة",
        "recent_projects_title" to "متابعة الطلبات الجارية"
    )

    fun get(key: String, lang: String): String {
        val map = if (lang == "ar") ar else en
        return map[key] ?: en[key] ?: key
    }
}
